"""Ediçao da coluna created_at no modelo atleta model

Revision ID: 31c0c75a4a9f
Revises: 79db92773a35
Create Date: 2025-10-22 13:45:08.712250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c0c75a4a9f'
down_revision: Union[str, Sequence[str], None] = '79db92773a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('atletas', sa.Column('categoria_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('atletas_categia_id_fkey'), 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'categorias', ['categoria_id'], ['pk_id'])
    op.drop_column('atletas', 'create_at')
    op.drop_column('atletas', 'categia_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('categia_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('atletas', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key(op.f('atletas_categia_id_fkey'), 'atletas', 'categorias', ['categia_id'], ['pk_id'])
    op.drop_column('atletas', 'categoria_id')
    op.drop_column('atletas', 'created_at')
    # ### end Alembic commands ###
